#!/usr/bin/env python3
import rospy
from service_quiz.srv import CustomServiceMessage, CustomServiceMessageResponse
from geometry_msgs.msg import Twist
import time

def callback(request):
    # Inițializăm publisher-ul pentru viteza robotului
    pub = rospy.Publisher('/cmd_vel', Twist, queue_size=10)
    move = Twist()
    
    # Așteptăm o secundă pentru ca publisher-ul să se înregistreze
    time.sleep(1)
    
    rospy.loginfo(f"Pornire simulare: latura {request.side} m, de {request.repetitions} ori.")

    for i in range(request.repetitions):
        for side_index in range(4):
            # 1. Mergem înainte
            move.linear.x = 0.2  # Viteza liniară (m/s)
            move.angular.z = 0.0
            pub.publish(move)
            # Timpul = Distanța / Viteză
            time.sleep(request.side / 0.2)

            # 2. Oprire scurtă
            move.linear.x = 0.0
            pub.publish(move)
            time.sleep(0.5)

            # 3. Rotire 90 grade (1.57 radiani)
            move.angular.z = 0.5 # Viteza unghiulară (rad/s)
            pub.publish(move)
            # Timpul = 1.57 rad / 0.5 rad/s = 3.14 secunde
            time.sleep(1.57 / 0.5)

            # 4. Oprire rotație
            move.angular.z = 0.0
            pub.publish(move)
            time.sleep(0.5)
            
    rospy.loginfo("Simulare finalizată cu succes!")
    return CustomServiceMessageResponse(success=True)

def square_service_server():
    rospy.init_node('service_server_node')
    # Definim serviciul: nume, tip mesaj, funcția de callback
    rospy.Service('move_robot_in_square', CustomServiceMessage, callback)
    rospy.loginfo("Serverul este gata să primească comenzi...")
    rospy.spin()

if __name__ == "__main__":
    try:
        square_service_server()
    except rospy.ROSInterruptException:
        pass
